//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TestExportScriptWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("TestExportScript");
		L.RegFunction("PrintGameobject", PrintGameobject);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PrintGameobject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
			TestExportScript.PrintGameobject(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

