//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_CanvasRendererWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.CanvasRenderer), typeof(UnityEngine.Component));
		L.RegFunction("SetColor", SetColor);
		L.RegFunction("GetColor", GetColor);
		L.RegFunction("EnableRectClipping", EnableRectClipping);
		L.RegFunction("DisableRectClipping", DisableRectClipping);
		L.RegFunction("SetMaterial", SetMaterial);
		L.RegFunction("GetMaterial", GetMaterial);
		L.RegFunction("SetPopMaterial", SetPopMaterial);
		L.RegFunction("GetPopMaterial", GetPopMaterial);
		L.RegFunction("SetTexture", SetTexture);
		L.RegFunction("SetAlphaTexture", SetAlphaTexture);
		L.RegFunction("SetMesh", SetMesh);
		L.RegFunction("Clear", Clear);
		L.RegFunction("GetAlpha", GetAlpha);
		L.RegFunction("SetAlpha", SetAlpha);
		L.RegFunction("GetInheritedAlpha", GetInheritedAlpha);
		L.RegFunction("SplitUIVertexStreams", SplitUIVertexStreams);
		L.RegFunction("CreateUIVertexStream", CreateUIVertexStream);
		L.RegFunction("AddUIVertexStream", AddUIVertexStream);
		L.RegFunction("New", _CreateUnityEngine_CanvasRenderer);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("hasPopInstruction", get_hasPopInstruction, set_hasPopInstruction);
		L.RegVar("materialCount", get_materialCount, set_materialCount);
		L.RegVar("popMaterialCount", get_popMaterialCount, set_popMaterialCount);
		L.RegVar("absoluteDepth", get_absoluteDepth, null);
		L.RegVar("hasMoved", get_hasMoved, null);
		L.RegVar("cullTransparentMesh", get_cullTransparentMesh, set_cullTransparentMesh);
		L.RegVar("hasRectClipping", get_hasRectClipping, null);
		L.RegVar("relativeDepth", get_relativeDepth, null);
		L.RegVar("cull", get_cull, set_cull);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_CanvasRenderer(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.CanvasRenderer obj = new UnityEngine.CanvasRenderer();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.CanvasRenderer.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetColor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			UnityEngine.Color arg0 = ToLua.ToColor(L, 2);
			obj.SetColor(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetColor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			UnityEngine.Color o = obj.GetColor();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EnableRectClipping(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			UnityEngine.Rect arg0 = StackTraits<UnityEngine.Rect>.Check(L, 2);
			obj.EnableRectClipping(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DisableRectClipping(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			obj.DisableRectClipping();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMaterial(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes<int>(L, 3))
			{
				UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.SetMaterial(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.Texture>(L, 3))
			{
				UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
				UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 2);
				UnityEngine.Texture arg1 = (UnityEngine.Texture)ToLua.ToObject(L, 3);
				obj.SetMaterial(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.CanvasRenderer.SetMaterial");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMaterial(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
				UnityEngine.Material o = obj.GetMaterial();
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2)
			{
				UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
				UnityEngine.Material o = obj.GetMaterial(arg0);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.CanvasRenderer.GetMaterial");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPopMaterial(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.SetPopMaterial(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPopMaterial(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Material o = obj.GetPopMaterial(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTexture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			UnityEngine.Texture arg0 = (UnityEngine.Texture)ToLua.CheckObject<UnityEngine.Texture>(L, 2);
			obj.SetTexture(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAlphaTexture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			UnityEngine.Texture arg0 = (UnityEngine.Texture)ToLua.CheckObject<UnityEngine.Texture>(L, 2);
			obj.SetAlphaTexture(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMesh(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			UnityEngine.Mesh arg0 = (UnityEngine.Mesh)ToLua.CheckObject(L, 2, typeof(UnityEngine.Mesh));
			obj.SetMesh(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAlpha(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			float o = obj.GetAlpha();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAlpha(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetAlpha(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInheritedAlpha(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)ToLua.CheckObject(L, 1, typeof(UnityEngine.CanvasRenderer));
			float o = obj.GetInheritedAlpha();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SplitUIVertexStreams(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 8)
			{
				System.Collections.Generic.List<UnityEngine.UIVertex> arg0 = (System.Collections.Generic.List<UnityEngine.UIVertex>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.UIVertex>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg1 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Color32> arg2 = (System.Collections.Generic.List<UnityEngine.Color32>)ToLua.CheckObject(L, 3, typeof(System.Collections.Generic.List<UnityEngine.Color32>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg3 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 4, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg4 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 5, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg5 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 6, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Vector4> arg6 = (System.Collections.Generic.List<UnityEngine.Vector4>)ToLua.CheckObject(L, 7, typeof(System.Collections.Generic.List<UnityEngine.Vector4>));
				System.Collections.Generic.List<int> arg7 = (System.Collections.Generic.List<int>)ToLua.CheckObject(L, 8, typeof(System.Collections.Generic.List<int>));
				UnityEngine.CanvasRenderer.SplitUIVertexStreams(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else if (count == 10)
			{
				System.Collections.Generic.List<UnityEngine.UIVertex> arg0 = (System.Collections.Generic.List<UnityEngine.UIVertex>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.UIVertex>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg1 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Color32> arg2 = (System.Collections.Generic.List<UnityEngine.Color32>)ToLua.CheckObject(L, 3, typeof(System.Collections.Generic.List<UnityEngine.Color32>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg3 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 4, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg4 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 5, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg5 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 6, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg6 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 7, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg7 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 8, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Vector4> arg8 = (System.Collections.Generic.List<UnityEngine.Vector4>)ToLua.CheckObject(L, 9, typeof(System.Collections.Generic.List<UnityEngine.Vector4>));
				System.Collections.Generic.List<int> arg9 = (System.Collections.Generic.List<int>)ToLua.CheckObject(L, 10, typeof(System.Collections.Generic.List<int>));
				UnityEngine.CanvasRenderer.SplitUIVertexStreams(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.CanvasRenderer.SplitUIVertexStreams");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateUIVertexStream(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 8)
			{
				System.Collections.Generic.List<UnityEngine.UIVertex> arg0 = (System.Collections.Generic.List<UnityEngine.UIVertex>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.UIVertex>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg1 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Color32> arg2 = (System.Collections.Generic.List<UnityEngine.Color32>)ToLua.CheckObject(L, 3, typeof(System.Collections.Generic.List<UnityEngine.Color32>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg3 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 4, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg4 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 5, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg5 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 6, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Vector4> arg6 = (System.Collections.Generic.List<UnityEngine.Vector4>)ToLua.CheckObject(L, 7, typeof(System.Collections.Generic.List<UnityEngine.Vector4>));
				System.Collections.Generic.List<int> arg7 = (System.Collections.Generic.List<int>)ToLua.CheckObject(L, 8, typeof(System.Collections.Generic.List<int>));
				UnityEngine.CanvasRenderer.CreateUIVertexStream(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				return 0;
			}
			else if (count == 10)
			{
				System.Collections.Generic.List<UnityEngine.UIVertex> arg0 = (System.Collections.Generic.List<UnityEngine.UIVertex>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.UIVertex>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg1 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Color32> arg2 = (System.Collections.Generic.List<UnityEngine.Color32>)ToLua.CheckObject(L, 3, typeof(System.Collections.Generic.List<UnityEngine.Color32>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg3 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 4, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg4 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 5, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg5 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 6, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg6 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 7, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg7 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 8, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Vector4> arg8 = (System.Collections.Generic.List<UnityEngine.Vector4>)ToLua.CheckObject(L, 9, typeof(System.Collections.Generic.List<UnityEngine.Vector4>));
				System.Collections.Generic.List<int> arg9 = (System.Collections.Generic.List<int>)ToLua.CheckObject(L, 10, typeof(System.Collections.Generic.List<int>));
				UnityEngine.CanvasRenderer.CreateUIVertexStream(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.CanvasRenderer.CreateUIVertexStream");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddUIVertexStream(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 7)
			{
				System.Collections.Generic.List<UnityEngine.UIVertex> arg0 = (System.Collections.Generic.List<UnityEngine.UIVertex>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.UIVertex>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg1 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Color32> arg2 = (System.Collections.Generic.List<UnityEngine.Color32>)ToLua.CheckObject(L, 3, typeof(System.Collections.Generic.List<UnityEngine.Color32>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg3 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 4, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg4 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 5, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg5 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 6, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Vector4> arg6 = (System.Collections.Generic.List<UnityEngine.Vector4>)ToLua.CheckObject(L, 7, typeof(System.Collections.Generic.List<UnityEngine.Vector4>));
				UnityEngine.CanvasRenderer.AddUIVertexStream(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else if (count == 9)
			{
				System.Collections.Generic.List<UnityEngine.UIVertex> arg0 = (System.Collections.Generic.List<UnityEngine.UIVertex>)ToLua.CheckObject(L, 1, typeof(System.Collections.Generic.List<UnityEngine.UIVertex>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg1 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Color32> arg2 = (System.Collections.Generic.List<UnityEngine.Color32>)ToLua.CheckObject(L, 3, typeof(System.Collections.Generic.List<UnityEngine.Color32>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg3 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 4, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg4 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 5, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg5 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 6, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector2> arg6 = (System.Collections.Generic.List<UnityEngine.Vector2>)ToLua.CheckObject(L, 7, typeof(System.Collections.Generic.List<UnityEngine.Vector2>));
				System.Collections.Generic.List<UnityEngine.Vector3> arg7 = (System.Collections.Generic.List<UnityEngine.Vector3>)ToLua.CheckObject(L, 8, typeof(System.Collections.Generic.List<UnityEngine.Vector3>));
				System.Collections.Generic.List<UnityEngine.Vector4> arg8 = (System.Collections.Generic.List<UnityEngine.Vector4>)ToLua.CheckObject(L, 9, typeof(System.Collections.Generic.List<UnityEngine.Vector4>));
				UnityEngine.CanvasRenderer.AddUIVertexStream(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.CanvasRenderer.AddUIVertexStream");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasPopInstruction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool ret = obj.hasPopInstruction;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hasPopInstruction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_materialCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			int ret = obj.materialCount;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index materialCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_popMaterialCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			int ret = obj.popMaterialCount;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index popMaterialCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_absoluteDepth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			int ret = obj.absoluteDepth;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index absoluteDepth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasMoved(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool ret = obj.hasMoved;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hasMoved on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cullTransparentMesh(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool ret = obj.cullTransparentMesh;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cullTransparentMesh on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasRectClipping(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool ret = obj.hasRectClipping;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hasRectClipping on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_relativeDepth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			int ret = obj.relativeDepth;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index relativeDepth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cull(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool ret = obj.cull;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cull on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_hasPopInstruction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.hasPopInstruction = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hasPopInstruction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_materialCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.materialCount = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index materialCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_popMaterialCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.popMaterialCount = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index popMaterialCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cullTransparentMesh(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.cullTransparentMesh = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cullTransparentMesh on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cull(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.CanvasRenderer obj = (UnityEngine.CanvasRenderer)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.cull = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cull on a nil value");
		}
	}
}

